import type { GeneratedAsset } from '../lib/types';
import { FileText, Film, Award, Maximize2, Copy, Check, Palette, X, Download } from 'lucide-react';
import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

interface AssetViewerProps {
  assets: GeneratedAsset[];
}

export function AssetViewer({ assets }: AssetViewerProps) {
  const [selectedAsset, setSelectedAsset] = useState<GeneratedAsset | null>(null);

  if (assets.length === 0) {
    return (
      <div className="h-full flex items-center justify-center">
        <div className="text-center text-gray-600">
          <div className="w-12 h-12 mx-auto mb-3 rounded-xl bg-gray-800/50 flex items-center justify-center">
            <FileText size={20} className="text-gray-600" />
          </div>
          <div className="text-sm font-mono mb-1">No assets yet</div>
          <div className="text-[10px] text-gray-700">Execute a campaign to generate content</div>
        </div>
      </div>
    );
  }

  return (
    <>
      <div className="space-y-3">
        {assets.map((asset) => (
          <AssetCard key={asset.id} asset={asset} onExpand={() => setSelectedAsset(asset)} />
        ))}
      </div>

      {/* Full-screen Modal */}
      <AnimatePresence>
        {selectedAsset && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/90 backdrop-blur-xl">
            <motion.div 
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              transition={{ duration: 0.2 }}
              className="bg-[#0a0e14] border border-cyan-500/30 w-full max-w-4xl max-h-[90vh] flex flex-col rounded-xl shadow-[0_0_100px_rgba(0,240,255,0.15)] overflow-hidden"
            >
              {/* Modal Header */}
              <div className="flex items-center justify-between p-4 border-b border-gray-800 bg-black/40">
                <div className="flex items-center gap-3">
                  {getAssetIcon(selectedAsset.type)}
                  <div>
                    <h3 className="font-orbitron text-lg text-white">{selectedAsset.title}</h3>
                    <div className="flex items-center gap-2 mt-0.5 text-[10px] text-gray-500 font-mono">
                      <span>{selectedAsset.type.replace('_', ' ').toUpperCase()}</span>
                      <span>•</span>
                      <span>Generated by {selectedAsset.generatedBy}</span>
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <CopyButton content={selectedAsset.content} />
                  <DownloadButton asset={selectedAsset} />
                  <button 
                    onClick={() => setSelectedAsset(null)} 
                    className="p-2 hover:bg-white/10 rounded-lg text-gray-400 hover:text-white transition-colors"
                  >
                    <X size={18} />
                  </button>
                </div>
              </div>

              {/* Modal Content */}
              <div className="flex-1 overflow-y-auto p-6 bg-black/20">
                <pre className="font-mono text-sm text-gray-300 whitespace-pre-wrap leading-relaxed">
                  {selectedAsset.content}
                </pre>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </>
  );
}

function AssetCard({ asset, onExpand }: { asset: GeneratedAsset; onExpand: () => void }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-gray-900/50 border border-gray-800 hover:border-cyan-500/30 rounded-lg p-4 group transition-all cursor-pointer"
      onClick={onExpand}
    >
      <div className="flex items-start gap-3">
        <div className="w-10 h-10 rounded-lg bg-gray-800 flex items-center justify-center shrink-0">
          {getAssetIcon(asset.type)}
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <span className="text-[10px] font-mono text-gray-500 uppercase tracking-wider">
              {asset.type.replace('_', ' ')}
            </span>
            <span className="text-[10px] text-gray-600">•</span>
            <span className="text-[10px] text-gray-600">{asset.generatedBy}</span>
          </div>
          <h4 className="font-semibold text-sm text-gray-200 truncate">{asset.title}</h4>
          <p className="text-[11px] text-gray-500 line-clamp-2 mt-1 leading-relaxed">
            {asset.content.slice(0, 150)}...
          </p>
        </div>
        <button className="p-2 opacity-0 group-hover:opacity-100 hover:bg-white/10 rounded-lg text-gray-400 hover:text-cyan-400 transition-all">
          <Maximize2 size={14} />
        </button>
      </div>
    </motion.div>
  );
}

function getAssetIcon(type: GeneratedAsset['type']) {
  switch (type) {
    case 'strategy': return <Award size={18} className="text-purple-400" />;
    case 'video_prompt': return <Film size={18} className="text-pink-400" />;
    case 'research_report': return <FileText size={18} className="text-blue-400" />;
    case 'design_blueprint': return <Palette size={18} className="text-orange-400" />;
    default: return <FileText size={18} className="text-gray-400" />;
  }
}

function CopyButton({ content }: { content: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <button 
      onClick={handleCopy}
      className="flex items-center gap-1.5 px-3 py-1.5 bg-gray-800 hover:bg-gray-700 rounded-lg text-xs font-mono text-gray-300 transition-colors"
    >
      {copied ? <Check size={14} className="text-green-400" /> : <Copy size={14} />}
      <span>{copied ? 'Copied!' : 'Copy'}</span>
    </button>
  );
}

function DownloadButton({ asset }: { asset: GeneratedAsset }) {
  const handleDownload = () => {
    const blob = new Blob([asset.content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${asset.title.replace(/\s+/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <button 
      onClick={handleDownload}
      className="flex items-center gap-1.5 px-3 py-1.5 bg-cyan-500/20 hover:bg-cyan-500/30 rounded-lg text-xs font-mono text-cyan-400 transition-colors"
    >
      <Download size={14} />
      <span>Download</span>
    </button>
  );
}
